### ISSUE TITLE
Compatibility with Knockout v3.3.0

### ISSUE THREAD

**Issue by bennyn** [brianmhunt/knockout-secure-binding#39]
:+1: for creating a Knockout version which does not conflict with strict Content Security Policies. I really like that efforts are made to realize that.

What are the future plans? Because 9 days ago Knockout version 3.3.0 has been released. Are you migrating that version?

**Comment by brianmhunt** [comment]
Thanks @bennyn -- I plan to keep KSB up to date with KO.

Have you experienced any issues using them together?

Cheers

**Comment by brianmhunt** [comment]
Going to close this as there is no specific issue to fix. KSB should be working just fine with KO 3.3 – but please advise and I'll re-open if there is a specific problem. Cheers
