### ISSUE TITLE
When no "()" in binding function/callback [3.2.0], then knockout binding doesn't work at all

### ISSUE THREAD

**Issue by alundiak** [brianmhunt/knockout-secure-binding#43]
I have knockout `3.2.0`
And I'm using https://github.com/brianmhunt/knockout-secure-binding (`v0.5.1` - 2014-10-07)
I follow docs [The "click" binding](http://knockoutjs.com/documentation/click-binding.html) to setup click binding.
My code:
```html
<a target="_blank" href="#" 
 data-bind="
  attr: {href: downloadReportURL()}, 
  click: setInProgress, 
  enable: enableDownloadButton()">Download</a>
```

```js
this.inProgress(false); // simple observable

this.downloadReportURL = ko.observable(''); // simple observable

this.setInProgress = function(){ // simple function
    this.inProgress(true);
}.bind(this);

this.enableDownloadButton = ko.computed(function(){  // computed function
   return !this.inProgress() && !!this.downloadReportURL();
}, this);
```

Then as result, **Knockout kind stuck on click binding**:
- `href` is set,
- `setInPogres()` function is executed, but `click` simply doesn't work (clicking on hyperlink causes NOTHING), feels like preventedDefault executed
- `setInPogres()` function is executed, but computed function `enableDownloadButton ` doesn't see change of observable `inProgress`.
- `enable` binding doesn't work, because after changing `inProgress()` computed function should have been executed, but not
- [reproduced not always] If I change `click: setInPogress` and put it as first in binding seqeunce, then all functions after (right) it will not work. All left binding functions will work.

So when I change code to this: `click: setInProgress()` - adding `()` everything works fine - NATIVE A HREF work as expected, **but click binding doesn't work as expected**, as I understand from docs.

*UPD*:
When I change my HTML code from `A` to `BUTTON`:
```html
<button data-bind="
 click: setInProgress, 
 attr: {href: downloadReportURL}, 
 enable: enableDownloadButton()">Download</button>
```
`click` binding works, `href` binding can not be applied and `enable` binding works.
But it's not what i needed. :)
**So looks like, Knockout Binding behaves differently, when control element is `A`**

**Is this kind of bug?** Can someone reproduce/verify with latest Knockout release? (I can't for now)/
Are docs up to date?

My Secure binding settings:
```
ko = require('knockout');
require('knockout-secure-binding');
ko.bindingProvider.instance = new ko.secureBindingsProvider({
  attribute: 'data-bind'//,        // default "data-sbind"
  //globals: window,               // default {}
  //bindings: ko.bindingHandlers,  // default ko.bindingHandlers
  //noVirtualElements: false       // default true
});
```

PS1. Interesting, that this approach - with NO `()` in function WORKS fine with Knockout v `2.3.0` (I have codebase of my old application, and it still works)

PS. This behavior was reproduced by me time ago also with another code, and it was 3.2.0 version also. No ability to provide steps and code, but behavior was the same - using `()` or not using, but binding WAS not click and was not `A/BUTTON` question.

FYI @mbest @brianmhunt

PS. Copied from here: https://github.com/knockout/knockout/issues/1978 due to potential reason of issue in KSB.

**Comment by brianmhunt** [comment]
Thank for copying this over @alundiak – Let's set up a jsFiddle demonstrating the problem.  Feel free to get one started, or I'll set one up when I get a bit more time to sit with this.

Cheers

**Comment by alundiak** [comment]
@brianmhunt I'm almost ready with my jsfiddle. 90% sure, that it's not even KSB issue. Will update both github issues in a while.

**Comment by alundiak** [comment]
@brianmhunt I do close this issue, due to found solution on initial knockout repo issue.

**Comment by brianmhunt** [comment]
Cool!  :snowflake:
